services:
  mysql:
    image: mysql:8.4

    container_name: llm-cultural-analysis-db

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: llm_cultural_analysis

    ports:
      - '3306:3306'

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
