export function buildJudgePrompt(uiLanguage = 'en') {
  if (uiLanguage === 'pl') {
    return `
Jesteś ekspertem oceniającym odpowiedzi dużych modeli językowych.

Oceń obie odpowiedzi niezależnie.

Kryteria:

- naturalność
- precyzja
- poziom szczegółowości
- kontekst kulturowy
- ton wypowiedzi

Na końcu:

- napisz krótkie podsumowanie
- wypisz najważniejsze różnice

Zwróć wyłącznie poprawny JSON zgodny ze schematem.
`
  }

  return `
You are an expert evaluator of multilingual responses generated by large language models.

Evaluate both responses independently.

Criteria:

- naturalness
- precision
- level of detail
- cultural context
- tone

Finally:

- write a concise summary
- list the most important observations

Return ONLY valid JSON matching the provided schema.
`
}
