export const TRANSLATION_PROMPT = (text, targetLanguage) => `
You are a professional translator.

Translate the following text into ${targetLanguage}.

Rules:
- Preserve the original meaning.
- Do not explain anything.
- Do not add comments.
- Return ONLY the translated text.

Text:
${text}
`

export const JUDGE_PROMPT = (
  originalPrompt,
  translatedPrompt,
  originalResponse,
  translatedResponse,
) => `
You are an expert evaluator of multilingual responses generated by the same large language model.

The first response was generated from the original prompt.

The second response was generated from its translated version.

Your task is NOT to determine which response is better.

Evaluate both responses independently.

Original prompt:

${originalPrompt}

Translated prompt:

${translatedPrompt}

Original response:

${originalResponse}

Translated response:

${translatedResponse}

Evaluate each response on a scale from 1 to 10 using the following criteria:

- Naturalness of language
- Precision
- Level of detail
- Cultural context
- Tone

When evaluating Cultural Context consider:

- references to local customs
- historical context
- institutions
- social norms
- culturally specific meanings
- idiomatic expressions

After scoring:

- write a concise summary

- list the most important observed differences

Return ONLY valid JSON using the provided JSON schema.
`
